# Generated by Django 3.2.4 on 2021-06-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('idpais', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID del pais')),
                ('pais', models.CharField(max_length=40, verbose_name='Nombre del pais')),
            ],
        ),
        migrations.CreateModel(
            name='periodista',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Rut del periodista')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('nombre_c', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.IntegerField(verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=90, verbose_name='Direccion')),
                ('email', models.CharField(max_length=50, verbose_name='Email ')),
                ('contrasena', models.CharField(max_length=50, verbose_name='contraseña')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais', verbose_name='Pais')),
            ],
        ),
    ]
